### ISSUE TITLE
Node won't restart

### ISSUE THREAD

**Issue by chris-remus** [Agoric/testnet-notes#37] opened 2021-08-28 01:04 UTC
Error - 

```Aug 26 17:14:54 cflow-agoric-tn-01 ag-chain-cosmos[2233165]: Cannot initialize Controller ExitCode: v10:zoe exited: I/O error```

See full logs -

https://hackmd.io/yjJrpQGfT1eoqmasn1I6kw?view

**Comment by dckc** [comment] 2021-08-30 16:59
Thanks for the report; this `Bad address` error in the zoe vat looks like a duplicate of #33 .

**Closed by dckc** 2021-08-30 16:59 UTC
