### ISSUE TITLE
Can't connect to RPC node to complete AMM tasks

### ISSUE THREAD

**Issue by chris-remus** [Agoric/testnet-notes#36] opened 2021-08-28 00:59 UTC
I've tried everything I can think of to complete the AMM tasks. I tried with the public RPC node and a private one shared by a community member.

With public RPC - 

```
ag-solo_1  | 2021-08-27T15:12:03.384Z SwingSet: vat: v11: waiting for wallet to initialize
ag-solo_1  | 2021-08-27T15:12:03.484Z outbound: invoking deliverator; 2 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
ag-solo_1  | 2021-08-27T15:12:04.121Z chain-cosmos-sdk: gas estimate: 48392
ag-solo_1  | 2021-08-27T15:12:04.122Z chain-cosmos-sdk: delivering to chain (trips=5) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
ag-solo_1  |   [ 14, '14:12:deliver:ro+336035:getCurrentAmount:rp-51;[]' ],
ag-solo_1  |   [ 15, '15:12:deliver:ro+336028:getMyAddress:rp-52;[]' ],
ag-solo_1  |   [
ag-solo_1  |     16,
ag-solo_1  |     '16:12:deliver:ro+336028:update:rp-53:ro-22;["depositFacet",{"@qclass":"slot","iface":"Alleged: contact","index":0}]'
ag-solo_1  |   ]
ag-solo_1  | ] 12
ag-solo_1  | 2021-08-27T15:12:05.116Z chain-cosmos-sdk: gas estimate: 48612
ag-solo_1  | 2021-08-27T15:12:36.993Z outbound: invoking deliverator; 6 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
ag-solo_1  | 2021-08-27T15:12:37.495Z chain-cosmos-sdk: delivering to chain (trips=6) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
ag-solo_1  |   [
ag-solo_1  |     17,
ag-solo_1  |     '17:17:deliver:ro+336022:getId:rp-54:ro+336034;[{"@qclass":"slot","iface":"Alleged: Zoe Invitation brand","index":0}]'
ag-solo_1  |   ],
ag-solo_1  |   [
ag-solo_1  |     18,
ag-solo_1  |     '18:17:deliver:ro+336022:has:rp-55:ro-22;[{"@qclass":"slot","iface":"Alleged: contact","index":0}]'
ag-solo_1  |   ],
ag-solo_1  |   [ 19, '19:17:deliver:ro+336032:getInvitationIssuer:rp-56;[]' ],
ag-solo_1  |   [ 20, '20:17:deliver:rp-56:getBrand:rp-57;[]' ],
ag-solo_1  |   [
ag-solo_1  |     21,
ag-solo_1  |     '21:17:deliver:rp-57:isMyIssuer:rp-58:rp-56;[{"@qclass":"slot","index":0}]'
ag-solo_1  |   ],
ag-solo_1  |   [ 22, '22:17:deliver:rp-57:getDisplayInfo:rp-59;[]' ]
ag-solo_1  | ] 17
ag-solo_1  | 2021-08-27T15:12:50.477Z chain-cosmos-sdk: Error: post failed: Post "http://164.90.247.20:26657": EOF
```

And private RPC -

```
ag-solo_1  | 2021-08-27T16:42:17.548Z chain-cosmos-sdk: delivering to chain (trips=2) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [] 158
ag-solo_1  | 2021-08-27T16:42:18.597Z chain-cosmos-sdk: gas estimate: 48323
ag-solo_1  | 2021-08-27T16:42:18.598Z chain-cosmos-sdk: delivering to chain (trips=3) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [] 158
ag-solo_1  | Open CapTP connection to ws://0.0.0.0:8000/private/captp...2021-08-27T16:42:18.856Z web: 127.0.0.1:46586[1]: new WebSocket /private/captp?accessToken=Pjo-_E8MHpVLbjTvYnS6KwL6Qt2gWoAeqe4bn2xc26th4QsFC7pinsMRRSen04-O
ag-solo_1  | oagoric: deploy: Don't need our provides: wallet
ag-solo_1  | 2021-08-27T16:42:18.973Z web: 127.0.0.1:46586[1]: client closed
ag-solo_1  | 2021-08-27T16:42:19.435Z chain-cosmos-sdk: Resynchronizing 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a sequence number from 1 to 42
ag-solo_1  | 2021-08-27T16:42:20.489Z chain-cosmos-sdk: gas estimate: 48323
ag-solo_1  | 2021-08-27T17:18:17.138Z web: GET /console/login/LoginForm.jsp 404 166 - 5.519 ms
ag-solo_1  | 2021-08-27T18:20:20.715Z web: GET http://example.com/ 200 4328 - 27.007 ms
ag-solo_1  | 2021-08-27T23:24:35.677Z web: GET / 200 4328 - 11.977 ms
ag-solo_1  | 2021-08-27T23:24:36.611Z web: GET /favicon.ico 404 150 - 6.844 ms
ag-solo_1  | 2021-08-27T23:53:57.351Z web: GET / 200 4328 - 3.884 ms
ag-solo_1  | 2021-08-28T00:02:36.383Z chain-cosmos-sdk: Error: post failed: Post "http://[PRIVATE_RPC_IP]:26657": EOF
```

I believe both AMM tasks would have been completed successfully if it wasn't for these issues.

**Comment by dckc** [comment] 2021-08-30 16:58
Thanks for the report; this `post failed` problem looks like a duplicate of #30 .

**Closed by dckc** 2021-08-30 16:58 UTC
