### ISSUE TITLE
Cannot swap RUN -> BLD

### ISSUE THREAD

**Issue by kinrokinro** [Agoric/testnet-notes#3] opened 2021-05-08 11:47 UTC
Subj, the transaction starts (funds are debited), but after a while they are returned back and nothing happens.

_Edit: This seems to be a known issue: https://github.com/Agoric/dapp-treasury/issues/28 --@dckc_

_Edit 2: **offer safety is protecting testnet participants from a bug in the treasury contract!** Zoe is refunding the offer because the bug in the treasury caused an offer safety violation._

**Comment by dckc** [comment] 2021-05-08 11:51
Do you know which transaction starts? Can you point to it in the explorer?

Also, can you give more detail on the steps you took? Did you accept the offer in your wallet?

**Comment by dckc** [comment] 2021-05-08 11:53
Someone suggested a lack of liquidity in the run bld pool. Does the page for opening a vault give any clues about that?

**Comment by dckc** [comment] 2021-05-08 11:54
@rowgraus @katelynsills @michaelfig any clues?

**Comment by kinrokinro** [comment] 2021-05-08 11:59
> Someone suggested a lack of liquidity in the run bld pool. Does the page for opening a vault give any clues about that?

Nope, but that sounds logic.

**Comment by Gotogu** [comment] 2021-05-08 12:24
Asking for a cotation leads to a transaction ID in the explorer (Setting a Input quantity and waiting for the Estimated output):
https://testnet.explorer.agoric.net/transactions/51DB0E867D232E29E847C7E2D9CD249E8577DA2DFD55F7E08FF31318C2BB31F2

After hitting "swap", multiple transaction are displayed:

https://testnet.explorer.agoric.net/transactions/F24EEF3C6FB2766E73BBB4C55367750270FAF93B5741CAF312977AE8CA462CB6
https://testnet.explorer.agoric.net/transactions/E03A7CEB68FA759A7C5C1617FC805BA41B0D45EF77BA81DD6F4FAEE8D508524B
https://testnet.explorer.agoric.net/transactions/8F912E5F2242B5FE5FB90C1AF6F3E5D851C1121C9B1355806000B1316F779F89
...

After confirming the offer, multiple transaction again: 

https://testnet.explorer.agoric.net/transactions/BD1E46F710F65A0695BBD2C2F32ED9442658478ECAF984C0A4ECA909BE861444
https://testnet.explorer.agoric.net/transactions/AEAF1279327C9069E8ACB6E24F409F245986746FA0602225D8AB26ADA374A3D9
https://testnet.explorer.agoric.net/transactions/BD70C9EF5423FF6D16495F11899FF9999BB0CCE1FDFFDF41E4757DCE7EE0D353
...

**Comment by paddyson79** [comment] 2021-05-08 13:02
experiencing the same issue
![Bildschirmfoto 2021-05-08 um 14 57 01](https://user-images.githubusercontent.com/35639331/117540204-48107180-b00e-11eb-8212-be0413d6e6f3.png)

tx is pending run is withdrawn from my wallet balance but returned later

**Comment by dckc** [comment] 2021-05-08 15:40
This seems to be a known issue: https://github.com/Agoric/dapp-treasury/issues/28

**Comment by dckc** [comment] 2021-05-08 15:44
Interesting: **offer safety is protecting testnet participants from a bug in the treasury contract!** Zoe is refunding the offer because the bug in the treasury caused an offer safety violation.

**Comment by dckc** [comment] 2021-05-11 21:28
This was addressed by restarting the chain on [agorictest-12](https://github.com/Agoric/agoric-sdk/releases/tag/agorictest-12) including a work-around:

 - [99a34c6cb](https://github.com/Agoric/agoric-sdk/commit/99a34c6cbd49b076a6965bcda318ae7647a4b106) chore: switch to classic multipoolAutoswap

For the root cause bug and a fix for it, stay tuned to:
https://github.com/Agoric/dapp-treasury/issues/28
https://github.com/Agoric/agoric-sdk/pull/3060

**Closed by dckc** 2021-05-11 21:28 UTC
Labels: bug, duplicate
