### ISSUE TITLE
Faucet not working due to provisioning logic bug

### ISSUE THREAD

**Issue by Tomas-Eminger** [Agoric/testnet-notes#25] opened 2021-08-23 16:26 UTC
Go to Discord, navigate to testnet-faucet channel
Type: !faucet client agoric1kj8hmeca3rw2cndj6zu98hfqmcqwgpxhq8l4ay
It should top wallet with funds, but error occurs:
@EmiT | RBF, Sorry, the faucet failed

**Comment by dckc** [comment] 2021-08-23 17:01
@michaelfig is it clear to you what's going on?

in `#bot-control` I see:

```
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = egress not found: key not found
```
https://discord.com/channels/585576150827532298/755903970907652291/879395866752979014

**Comment by michaelfig** [comment] 2021-08-23 17:35
> @michaelfig is it clear to you what's going on?

Argh.  I switched a condition, and was getting things exactly backward (only provision if already provisioned)!  This is fixed now.

**Comment by dckc** [comment] 2021-08-23 18:43
I updated the title to indicate the root cause.

**Closed by dckc** 2021-08-23 18:43 UTC

**Comment by yelllowsin** [comment] 2021-08-24 11:20
@dckc I am still having issues with the faucet, can't get tokens to be delivered to this address. I am feeling hopeless already, I have tried many times, but still none worked for me: https://testnet.explorer.agoric.net/account/agoric1qr2s775y7umrm90ykjtfnhyk76zsrapx3z2xm8
